# Generated by Django 6.0.7 on 2026-09-15 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comunidades", "0002_comunidad_gestores"),
    ]

    operations = [
        migrations.AddField(
            model_name="comunidad",
            name="instagram",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="comunidad",
            name="nivel_actividad",
            field=models.CharField(
                choices=[
                    ("activo", "Activo"),
                    ("poco_activo", "Poco activo"),
                    ("inactivo", "Inactivo"),
                    ("sin_verificar", "Sin verificar"),
                ],
                default="sin_verificar",
                max_length=20,
            ),
        ),
    ]
