# Generated by Django 6.0.7 on 2026-09-15 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comunidades", "0003_comunidad_instagram_comunidad_nivel_actividad"),
    ]

    operations = [
        migrations.CreateModel(
            name="Facultad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=20, unique=True)),
                ("descripcion", models.CharField(blank=True, max_length=150)),
            ],
            options={
                "verbose_name_plural": "facultades",
                "ordering": ["nombre"],
            },
        ),
        migrations.AddField(
            model_name="comunidad",
            name="facultad",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="comunidades",
                to="comunidades.facultad",
            ),
        ),
    ]
