# Generated by Django 6.0.7 on 2026-09-16 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comunidades", "0004_facultad_comunidad_facultad"),
    ]

    operations = [
        migrations.AddField(
            model_name="comunidad",
            name="carrera",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="comunidad",
            name="fundado",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="comunidad",
            name="lugar_reuniones",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="comunidad",
            name="membresia",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="comunidad",
            name="reuniones",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.CreateModel(
            name="PublicacionInstagram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                ("agregada_en", models.DateTimeField(auto_now_add=True)),
                (
                    "comunidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publicaciones_instagram",
                        to="comunidades.comunidad",
                    ),
                ),
            ],
            options={
                "ordering": ["orden", "agregada_en"],
            },
        ),
    ]
