# Generated by Django 6.0.7 on 2026-09-16 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidades', '0006_comunidad_carrera_comunidad_fundado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacioninstagram',
            name='imagen',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='publicacioninstagram',
            name='titulo',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
